### ISSUE TITLE
Rename `sendPOST` to `sendPost`

### ISSUE THREAD

**Issue by ThomasLandauer** [Codeception/module-rest#20]
Reasons:
* Consistency with `lib-innerbrowser`s `sendAjaxPostRequest()`, see e.g. https://codeception.com/docs/modules/Symfony#sendAjaxPostRequest
* [PSR-1](https://www.php-fig.org/psr/psr-1/) compliance: 
    > Method names MUST be declared in camelCase

And, of course, the same for `sendGET`, `sendDELETE`, etc.

Suggested upgrade path, according to semantic versioning:
1. Create `sendPost` in next minor version (i.e. v1.3)
2. Keep `sendPOST` as alias, but deprecate it.
3. Remove `sendPOST` in next major version (i.e. v2.0)

**Comment by SamMousa** [comment]
Actually, in PHP function names are not case sensitive.
So we can just rename the function and that is not a break in BC.
