### ISSUE TITLE
Rename `deleteHeader()` to `unsetHttpHeader()`

### ISSUE THREAD

**Issue by ThomasLandauer** [Codeception/module-rest#22]
To be consistent with all other header functions: `haveHttpHeader()` (to which it is the counterpart), `seeHttpHeader()`, `seeHttpHeaderOnce()`, etc.

Also in [lib-innerbrowser](https://github.com/Codeception/lib-innerbrowser/blob/master/src/Codeception/Lib/InnerBrowser.php#L384)

**Comment by ThomasLandauer** [comment]
Actually, "delete" isn't really the right term here. I'd say: Either **unsetHttpHeader()**, or (to be consistent with `have...`) **dontHaveHttpHeader()**

**Comment by SamMousa** [comment]
A PR to fix this could be implemented without breaking BC. Just add an alias for the "wrong" function name and mark it deprecated.
Move the implementation to the "right" function name.

**Comment by ThomasLandauer** [comment]
If you merge this, I'll do the same in lib-innerbrowser.
