### ISSUE TITLE
Abandoned dependency

### ISSUE THREAD

**Issue by dereuromark** [Codeception/module-rest#24]
You use an abandoned dependency:
https://github.com/Codeception/module-rest/blob/master/composer.json#L16

See https://github.com/FlowCommunications/JSONPath/pull/51 and successor https://github.com/SoftCreatR/JSONPath

**Comment by SamMousa** [comment]
This fork however requires php > 7.2, so we cannot use it yet.

**Comment by SamMousa** [comment]
I hope we drop support for < 7.4 instead ;-)

**Comment by ddrv** [comment]
the `flow/jsonpath` package also uses `psr-0` autoloading, this blocks the `composer` upgrade to version `2.0`

Maybe temporarily move the code of the `flow/jsonpath` library to this package?

**Comment by DavertMik** [comment]
jsonpath is optional here - not everyone needs it
so we can probably remove it from the dependencies.

but actually yes, we can release `module-rest` 2.0 with this library replaced.

**Comment by SoftCreatR** [comment]
For PHP 5.4 - 7.0:
https://github.com/SoftCreatR/JSONPath/tree/oldphp

For PHP 7.1 - 8.0:
https://github.com/SoftCreatR/JSONPath

Just in case, that you need a solution. I've also just released v0.5.1, so migrating shouldn't be a problem. Simply replace

`"flow/jsonpath": "^0.5",` with `"softcreatr/jsonpath": "^0.5 || ^0.7"`

This should install v0.5.1 or v0.7.2, depending on the installed PHP version (5.4+).

**Comment by Naktibalda** [comment]
Released as 1.2.6

**Comment by Ravetracer** [comment]
Hi.
I'm using JSONPath in my tests in the REST module and still get this annoying error, that "data()" is deprecated.

The warning is raised (via softcreatr/jsonpath) in
`src/Codeception/Util/JsonArray.php`
line 90
`return (new JSONPath($this->jsonArray))->find($jsonPath)->data();`

The solution would be
`return (new JSONPath($this->jsonArray))->find($jsonPath)->getData();`

Changing dependencies just don't help here.

**Comment by Naktibalda** [comment]
Please raise a pull request or a new issue.
