### ISSUE TITLE
Drop `softcreatr/jsonpath` dependency?

### ISSUE THREAD

**Issue by ThomasLandauer** [Codeception/module-rest#36]
At https://github.com/Codeception/module-rest/issues/24#issuecomment-714807087 @DavertMik said this dependency could be dropped completely, and have users install it manually - like `hoa/console` at https://codeception.com/docs/02-GettingStarted#Interactive-Pause

I wrote https://github.com/Codeception/module-rest/pull/31 with this in mind. However, this would require some code changes, see https://github.com/Codeception/module-rest/pull/32#issuecomment-720770312

Is this going to happen? If not, I'd have to change the docs PR accordingly.

**Comment by Naktibalda** [comment]
I see no reason to drop this dependency.

JsonPath was an optional dependency when it was used by `codeception/codeception`.
If someone installs module-rest, it is very likely that they use JSON, and it isn't a big stretch to think that JsonPath can be useful.
Also the list of dependencies is short.
