### ISSUE TITLE
Calling JSONPath::data() is deprecated, please use JSONPath::getData() instead.

### ISSUE THREAD

**Issue by mwi-gofore** [Codeception/module-rest#38]
After updating to 1.2.6, using `grabDataFromResponseByJsonPath(..)` results in

`Calling JSONPath::data() is deprecated, please use JSONPath::getData() instead.`

Which naturally fails the test unless most errors are ignored (which would be a very bad practice)

**Comment by HaruAtari** [comment]
+1
It throws in https://github.com/Codeception/module-rest/blob/master/src/Codeception/Util/JsonArray.php#L90

**Comment by mwi-gofore** [comment]
> +1
> It throws in https://github.com/Codeception/module-rest/blob/master/src/Codeception/Util/JsonArray.php#L90

Yea, got too late yesterday, but this should be a trivial fix

**Comment by mwi-gofore** [comment]
Ah. #37 was already done.. too slow this morning, might need more coffee

**Comment by Naktibalda** [comment]
Fixed by #37
