### ISSUE TITLE
Cannot seamlessly use REST and PHPBrowser assertion

### ISSUE THREAD

**Issue by nicholascus** [Codeception/module-rest#4]
I know many mix PHPBrowser and REST modules for testing of web applications. When used that way REST module functions can get page as a response or get redirection headers and load new page (which is already supported).
Though once new page is loaded with REST functions it is not available for PHPBrowser crawler based asserts functions (seeElement etc).
That happens because REST module when backed by PHPBrowser uses _request() method which is in contrast with _loadPage() intentionally missing initialisation of PHPBrowser::crawler.

I'm proposing adding REST module parameter which would be switching PHPBrowse based REST test to using _loadPage(). PR will follow.

```
$I->amOnPage('/');
$url = $I->grabAttributeFrom('#id', 'data-post-url');
$I->sendPost($url, $data);
//post does redirect to an url2
$new_object_id = $I->grabAttributeFrom('#new-object-info', 'new-object-id');  
//this fails because last page loaded into crawler of InnerBrowser shared between rest and phpbrowser is '/' from $I->amOnPage('') step
```

**Comment by Naktibalda** [comment]
The issue I have with this pull request is that you are using REST module to access HTML page.
PHPBrowser has very similar methods for making non-HTML requests:
https://codeception.com/docs/modules/PhpBrowser#sendAjaxPostRequest
https://codeception.com/docs/modules/PhpBrowser#sendAjaxGetRequest
https://codeception.com/docs/modules/PhpBrowser#sendAjaxRequest
But they don't load the page either.

If you really want to implement this change, I would prefer if you modified sendAjax methods in [lib-innerbrowser](https://github.com/Codeception/lib-innerbrowser/blob/1.3.0/src/Codeception/Lib/InnerBrowser.php#L1254-L1314) and not the REST module.

Though, I think, that what you are actually looking for is [submitForm](https://codeception.com/docs/modules/PhpBrowser#submitForm) to URL rather than HTML.

@DavertMik What do you think about all this?

**Comment by DavertMik** [comment]
Yeah, I agree with @Naktibalda  I would use 
https://codeception.com/docs/modules/PhpBrowser#sendAjaxPostRequest

for this purpose. And modify it as well

**Comment by Naktibalda** [comment]
I have an alternative solution - grab Location header and open it using PhpBrowser method:

```php
$I->stopFollowingRedirects();
$I->sendPost($url, $data);
$I->seeHttpHeader('Location');
$location = $I->grabHttpHeader('Location', true);
$I->startFollowingRedirects();
$I->amOnUrl($location);
```

**Comment by nicholascus** [comment]
Yep, I'm aware that there are workarounds, but such workarounds don't do good to the code and are not that easy to use when you work in a big team. You would need to explain to everybody what problem is and how and why to workaround it... which would be mostly waste of time. An interesting thing is that I didn't have people having problems with `sendAjaxPost` as people don't expect 'ajax' request to be loaded into 'browser'.

The reality is that on many projects you would use phpbrowser and rest module at the same time. 
You could question selection of sendForm vs sendPOST methods, but the difference would be in details which most of the team members do not need to keep in mind (or would not understand at all). To me, when project already have both modules enabled, it looks fine to use those interchangeably.

This PR is just supposed to solve the confusion which Codeception users have when they find that some of assert methods don't work as expected. This change in asserts behaviour has been made configurable with default to leave asserts behaviour as it was.

I would really prefer to have the flexibility to enable phpbrowser module asserts for requests executed with rest module functions, as that would save people some time and write a bit more relaxed test code when they want that (while 'off' default configuration for this feature would keep directing teams towards better understanding of difference between using of rest and phpbrowser methods while testing web).

**Comment by nicholascus** [comment]
I checked module-phpbrowser code and didn't see any nice way to introduce url option for sendForm. As for sendAjaxXXX functions I doubt it is intuitive that ajax request would load something into "browser" and make it available for assertions.

As for the need for function like that, it is useful, it saves some time where you frequently need to use it to create some objects. Sometimes there are no get method returning pages with the form, form are built with javascript but still as sent the backend generate new pages which could require some assertions on them. 

I've actually seen different people coming up with the same idea that sendPost is good to use in web tests. And then they were very confused on why they could do sendPost and after that to have assertion error when dump of the last page in console and output folder have page with content passing assertion.

So I strongly believe that something need to be done to facilitate the use case. Options are:
- to introduce new a function to PHPBrowser;
- to redesign sendForm method... e.g. add locator ['bareurl' => '/xxx/yyy/zzz'] or something even more unnatural;
- to add alternative behaviour to REST module... which is I agree not natural either as that creates some unnecessary coupling between phpbrowser and rest modules.
- to modify sendAjaxXXX functions so they follow redirect and 'open page in phpbrowser' (which would probably require additional parameter or module config option as it is potentially breaking change) 
- not to do anything.
- could be that other options exist too...

@Naktibalda @DavertMik @ruudboon please share your thoughts.

**Comment by Naktibalda** [comment]
1. This use case isn't as popular as you think.
2. It is exactly what [_loadData ](https://codeception.com/docs/modules/PhpBrowser#_loadPage) helper method was introduced for.

> **_loadPage**
> 
> hidden API method, expected to be used from Helper classes
> 
> Opens a page with arbitrary request parameters. Useful for testing multi-step forms on a specific step.
> 
```php
// in Helper class
public function openCheckoutFormStep2($orderId) {
    $this->getModule('PhpBrowser')->_loadPage('POST', '/checkout/step2', ['order' => $orderId]);
}
```


If you want a general purpose method, you can implement it like this:
```php
// in Helper class
public function sendPostToPage($uri, array $params) {
    $this->getModule('PhpBrowser')->_loadPage('POST', $uri, $params);
}
```
