### ISSUE TITLE
Handling query parameters with HEAD HTTP method too

### ISSUE THREAD

**Issue by JasonBenett** [Codeception/module-rest#41]
Dear maintainers,

I think we should be able to pass query parameters the same way we are doing for GET methods with HEAD methods.
The concerned part seems to be there: https://github.com/Codeception/module-rest/blob/master/src/Codeception/Module/REST.php#L615-L622

What do you think?

**Comment by Naktibalda** [comment]
I think that you are right.

HEAD method must be supported in other places where GET is used too - [the line right below the block you marked](https://github.com/Codeception/module-rest/blob/beeb5a91a97d042273bf10f00063e9b8f541879a/src/Codeception/Module/REST.php#L623) and in [encodeApplicationJson method](https://github.com/Codeception/module-rest/blob/beeb5a91a97d042273bf10f00063e9b8f541879a/src/Codeception/Module/REST.php#L678)

[The most similar GET test](https://github.com/Codeception/module-rest/blob/beeb5a91a97d042273bf10f00063e9b8f541879a/tests/unit/Codeception/Module/RestTest.php#L207-L215) could be copied and adopted for testing HEAD.

**Comment by JasonBenett** [comment]
Awesome.
I will try to create the PR ASAP.
Thanks for your quick answer.

**Comment by Naktibalda** [comment]
Released as 1.2.8
