### ISSUE TITLE
How many build-in Filters do we have in jsonType feature

### ISSUE THREAD

**Issue by parisqian-misa** [Codeception/module-rest#46]
In the document, I could not find a list of build-in filters. I saw `url`, `date` and `empty` if-blocks in the code, are they filters?

One more thing, do we have anything like `json`/`object` filter, just like what we have with `array`, to detect whether the value part is a valid json object?

**Comment by W0rma** [comment]
Nowadays filters are documented here: https://codeception.com/docs/modules/REST#seeResponseMatchesJsonType

@Naktibalda @TavoNiievez I guess this issue can be closed?
