### ISSUE TITLE
[ feature request ] Support flags for json_encode() function

### ISSUE THREAD

**Issue by charescape** [Codeception/module-rest#51]
currently, `encodeApplicationJson` use `json_encode()` without flags, is there any way to add  default flags like:
```php
if ($parameters instanceof \JsonSerializable) {
    return json_encode($parameters, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
}
if (is_array($parameters) || $parameters instanceof \ArrayAccess) {
    $parameters = $this->scalarizeArray($parameters);
    return json_encode($parameters, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
}
```

https://github.com/Codeception/module-rest/blob/e314fe772c84ab1f2c0b80f435cc90efa58e7209/src/Codeception/Module/REST.php#L676-L692

**Comment by Naktibalda** [comment]
Yes, you can raise pull request :)

What issue would it solve for you?

**Comment by charescape** [comment]
@Naktibalda It can testing some edge cases, 

for example:

`JSON_INVALID_UTF8_IGNORE`
>Ignore invalid UTF-8 characters. Available as of PHP 7.2.0.

`JSON_INVALID_UTF8_SUBSTITUTE`
> Convert invalid UTF-8 characters to \0xfffd (Unicode Character 'REPLACEMENT CHARACTER') Available as of PHP 7.2.0.

https://www.php.net/manual/en/json.constants.php

**Comment by charescape** [comment]
@Naktibalda  And I have been busy recently, but I will try to submit a PR as soon as possible :)

**Comment by Naktibalda** [comment]
If you need to test that, you can use your own json_encode function.

Change `$I->sendPost($uri, $data);`  to `$I->sendPost($uri, json_encode($data, JSON_INVALID_UTF8_IGNORE));`

**Comment by charescape** [comment]
So, `$params` can be a string?

**Comment by charescape** [comment]
Yes, found it: https://github.com/Codeception/module-rest/blob/master/src/Codeception/Module/REST.php#L691

**Comment by charescape** [comment]
Thank you!
