### ISSUE TITLE
sendDELETE with request body

### ISSUE THREAD

**Issue by AndreasBilke** [Codeception/module-rest#55]
I tried to update module-rest from 1.2.7 to 1.3.0 and my tests with `sendDELETE` are failing because codeception no longer sends the `$params` as request body but as query parameters.

Is there a way to restore the old behaviour? Request bodys are allowed in HTTP DELETE and therefore should be supported by codeception too.

**Comment by Insolita** [comment]
RFC 7231 specifies that a DELETE request may include a body. Please, reverted these change or make them configurable

**Comment by Naktibalda** [comment]
I will revert it.

**Comment by Naktibalda** [comment]
@SamMousa This is the opposite of what was said in #44
Please discuss it :)

**Comment by Insolita** [comment]
@Naktibalda  - We use api by jsonApi spec, 

https://jsonapi.org/format/#crud-updating-to-many-relationships

![2021-04-17_15-04](https://user-images.githubusercontent.com/1847402/115104900-495df980-9f8e-11eb-8c21-549349db82d3.png)

**Comment by Insolita** [comment]
@SamMousa 
May be an additional method sendDeleteWithQueryString would be a suitable compromise

**Comment by SamMousa** [comment]
I propose instead having 2 params on the send delete method, one for body one for query string. If possible we should not break existing clients (again)

**Comment by SamMousa** [comment]
Ah wait, the issue was from 2018 but the fix was recent. Then I'm fine with reverting it and leaving it as is.

**Comment by SamMousa** [comment]
As evidenced few others ran into issues, so no need to make it harder than needed.

**Comment by Naktibalda** [comment]
Both linked pull requests must be merged and released:
https://github.com/Codeception/lib-innerbrowser/pull/38
https://github.com/Codeception/module-rest/pull/56

I will release new versions in a few days.

**Comment by Naktibalda** [comment]
I released this change as module-rest 1.3.1 and lib-innerbrowser 1.5.0
