### ISSUE TITLE
sendPOST, sendGET must return response

### ISSUE THREAD

**Issue by DavertMik** [Codeception/module-rest#64]
It is not quite intuitive that you need to use `$I->grabResponse`

**Comment by Naktibalda** [comment]
nobody reads these feature requests :)

**Comment by W0rma** [comment]
Seems like https://github.com/Codeception/module-rest/commit/29aa9270fafd54943708260ceea4336331dbff66 already implemented this feature request.

It was released in version [1.4.0](https://github.com/Codeception/module-rest/releases/tag/1.4.0)

@Naktibalda @TavoNiievez I guess this issue can be closed?
