### ISSUE TITLE
[PHP8.1] Upgrade to JSONPath 0.8 to fix deprecated warnings

### ISSUE THREAD

**Issue by pbojan** [Codeception/module-rest#69]
Would be nice to upgrade to JSONPath 0.8.0 to be able to fully use this with PHP 8.1 without any deprecated warnings:
https://github.com/SoftCreatR/JSONPath/releases/tag/0.8.0

> Note: With this version PHP 7 is not supported anymore.

**Comment by Naktibalda** [comment]
Please raise pull request

**Comment by pbojan** [comment]
Pull request: https://github.com/Codeception/module-rest/pull/70

**Comment by pbojan** [comment]
@Naktibalda can you check the PR and let me know if something else needs changing?
