### ISSUE TITLE
Return type of grabHttpHeader should be string|array|null

### ISSUE THREAD

**Issue by iweindesmedt** [Codeception/module-rest#84]
... so that it matches the return type of `...->getInternalResponse()->getHeader()`

I'm not sure where the `ActorAction`s are generated, but those generated methods should also match this return type.

https://github.com/Codeception/module-rest/blob/master/src/Codeception/Module/REST.php#L313

**Comment by Naktibalda** [comment]
Released as 3.2.0 https://github.com/Codeception/module-rest/releases/tag/3.2.0
