### ISSUE TITLE
BC breaks in patch release - please revert immediately

### ISSUE THREAD

**Issue by dereuromark** [Codeception/module-rest#93]
https://github.com/Codeception/module-rest/compare/3.3.0...3.3.1#diff-486d3eb6ce59019d27ba0aff3da4ef44480b769f45f54ae1db9c869fb77b126bL649
causes fatal errors on our complete test harness

> PHP Fatal error:  Declaration of SprykerTest\Glue\Testify\Helper\GlueRest::execute($method, $url, $parameters = [], $files = []) must be compatible with Codeception\Module\REST::execute(string $method, string $url, ArrayAccess|JsonSerializable|array|string $parameters = [], array $files = []): ?string in /home/runner/work/suite/suite/vendor/spryker/testify/tests/SprykerTest/Glue/Testify/_support/Helper/GlueRest.php on line 569

Please revert BC breaking changes (e.g. signature changes like type additions) for a patch release
This should only go into a major.

**Comment by Naktibalda** [comment]
Oops, I completely forgot about that change, reverted in 3.3.2 https://github.com/Codeception/module-rest/compare/3.3.1...3.3.2
