### ISSUE TITLE
Support PHP 7.4 and 8.1 at same time in 2.0.* ver.

### ISSUE THREAD

**Issue by xandros15** [Codeception/module-rest#94]
If I use 2.0.2 version and run `composer install` I got error with `softcreatr/jsonpath`, because don't support 8.1 in ^0.7.

Easier fix would be just add `softcreatr/jsonpath: ^0.5 | ^0.7 | ^0.8`  into composer.json.

I'm in middle of migration, so I need to use php 7.4 and 8.1 at same time.

**Comment by Naktibalda** [comment]
Released as [2.0.3](https://github.com/Codeception/module-rest/releases/tag/2.0.3)
